name: CI checks

on:
  push:

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    concurrency:
      group: ci-${{ github.head_ref || github.ref }}
      cancel-in-progress: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Yarn Install and Cache
        uses: graasp/graasp-deploy/.github/actions/yarn-install-and-cache@v1

      - name: Lint
        run: yarn check

      - name: Build
        run: yarn build
        env:
          VITE_VERSION: ci-check
